{ pkgs, ... }:

{
  # Generated by explicit.
  # Detected markers: Cargo.toml
  # Detected manifests: Cargo
  # - Detected rusqlite in the Rust dependencies; adding sqlite and pkg-config for native SQLite bindings.
  # - Detected libsqlite3-sys in the Rust dependencies; adding sqlite and pkg-config for native SQLite bindings.
  packages = [
    # Needed by explicit for repository inspection and generated hook workflows.
    pkgs.git
    # Needed by explicit runtime support inside generated environments.
    pkgs.jq
    # Needed to launch the sandboxed agent shell.
    pkgs.nono
    # Adding sqlite and pkg-config for native SQLite bindings.
    pkgs.pkg-config
    # Adding sqlite and pkg-config for native SQLite bindings.
    pkgs.sqlite
  ];
  # Detected Rust source files in the repository.
  languages.rust.enable = true;
}
